name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_HOST: ${{ secrets.HOST }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_APP_KEYS: ${{ secrets.APP_KEYS }}
          envkey_API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
          envkey_ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          envkey_TRANSFER_TOKEN_SALT: ${{ secrets.TRANSFER_TOKEN_SALT }}
          envkey_DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
          envkey_DATABASE_FILENAME: ${{ secrets.DATABASE_FILENAME }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET}}
          file_name: .env
          fail_on_empty: false

      - name: Move envfile to desired directory
        run: |
          mv /github/workspace/.env /backend/
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        
      - name: run install dependecies backend
        run: |
          cd backend
          npm install
     
      - name: run backend test
        run: |
          cd backend 
          npm run test
          
      - name: run install dependecies frontend
        run: |
          cd frontend
          npm install

      - name: run frontend test
        run: |
          cd frontend
          npm run build 
          npm test
