name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Create env file
        run: |
          echo "HOST=${{ secrets.HOST }}" > ./backend/.env
          echo "PORT=${{ secrets.PORT }}" >> ./backend/.env
          echo "APP_KEYS=${{ secrets.APP_KEYS }}" >> ./backend/.env
          echo "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" >> ./backend/.env
          echo "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" >> ./backend/.env
          echo "TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}" >> ./backend/.env
          echo "DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}" >> ./backend/.env
          echo "DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}" >> ./backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./backend/.env
          cat ./backend/.env
          working-directory: ${{ github.workspace }}
        
      - name: run install dependecies backend
        run: |
          cd backend
          npm install
     
      - name: run backend test
        run: |
          cd backend 
          npm run test
          
      - name: run install dependecies frontend
        run: |
          cd frontend
          npm install

      - name: run frontend test
        run: |
          cd frontend
          npm run build 
          npm test
