name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: Create env file
        run: |
          touch backend/.env
          echo ${{secrets.API_KEYS}} >> .env
        
      - name: run install dependecies backend
        run: |
          cd backend
          npm install
     
      - name: run backend test
        run: |
          cd backend 
          npm run test
          
      - name: run install dependecies frontend
        run: |
          cd frontend
          npm install

      - name: run frontend test
        run: |
          cd frontend
          npm run build 
          npm test
